### ISSUE TITLE
Strange Crash

### ISSUE THREAD

**Issue by zzApotheosis** [superckl/DPU#4]
Firstly, let me say thank you for making such a great mod!

On my single player world, my game crashed (server-side) and gave me this crash report:
https://drive.google.com/file/d/0B_wljXPJi507MHk4ZzIyOGh2cGc/view?usp=sharing

And the OpenEye report:
http://openeye.openmods.info/crashes/dbba5b9433167981ac030119d1643bd9

I'm not exactly sure why it crashed since I was just mining out space in my cave-house :P

**Comment by superckl** [comment]
In all honesty, I've stopped development of this mod. I'll look into updating this to the latest forge version though.

For now, you should be able to change the "Item Track Timer" field of the config to 0. The field is simply an optimization thing that you would only notice on really large servers. The crash won't happen then.

**Comment by superckl** [comment]
http://minecraft.curseforge.com/mc-mods/225343-dont-pick-up/files/2257369

Should fix the issue.
